#! perl

# $Id$

# pragmata
use strict;
use warnings;
use 5.008;

use lib qw( . lib ../lib ../../lib );
use lib $ENV{'PARROT_HOME'}.'/lib';
use Parrot::Test::Harness language => 'Wy',
                          compiler => 'wy.pbc';

